baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'ANAMIKA ANAND'
theme = "mainroad"
[menu]
[[menu.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10
[[menu.main]]
  name = 'CV'
  pageRef = '/CV'
  weight = 20
[[menu.main]]
  name = 'About'
  pageRef = '/about'
  weight = 30
[[menu.main]]
  name = 'Posts'
  pageRef = '/posts'
  weight = 20
 